// <auto-generated />
using System;
using EntityFrameworkCoreEducation.SimpleContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkCoreEducation.Migrations.SimpleContextMigrations
{
    [DbContext(typeof(DbSimpleContext))]
    [Migration("20240119170310_InitialSimpleContext")]
    partial class InitialSimpleContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityFrameworkCoreEducation.SimpleContext.Entities.Room", b =>
                {
                    b.Property<Guid>("RoomCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomCode");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("EntityFrameworkCoreEducation.SimpleContext.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoomCode")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoomCode");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EntityFrameworkCoreEducation.SimpleContext.Entities.Student", b =>
                {
                    b.HasOne("EntityFrameworkCoreEducation.SimpleContext.Entities.Room", null)
                        .WithMany("Students")
                        .HasForeignKey("RoomCode");
                });

            modelBuilder.Entity("EntityFrameworkCoreEducation.SimpleContext.Entities.Room", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
